#!/usr/bin/env python3
"""
Generate ui_twoProjector.h from twoProjector.ui
This is a fallback when Qt uic tool is not available.
"""

import xml.etree.ElementTree as ET
import os
import sys
from pathlib import Path

def extract_widget_names(ui_file):
    """Extract all widget object names from .ui file"""
    widgets = {}
    try:
        tree = ET.parse(ui_file)
        root = tree.getroot()

        # namespace handling
        ns = {'ui': 'http://www.trolltech.com/forms/'}

        # Find all widget elements
        for widget in root.findall('.//ui:widget', ns):
            name = widget.get('name')
            wtype = widget.get('class')
            if name and wtype:
                widgets[name] = wtype

        # Find all other elements with names (buttons, layouts, etc)
        for elem in root.iter():
            name = elem.get('name')
            tag = elem.tag.split('}')[-1] if '}' in elem.tag else elem.tag
            if name and name not in widgets and tag in ['pushButton', 'label', 'lineEdit', 'comboBox', 'spinBox', 'checkBox', 'radioButton', 'tabWidget', 'toolButton', 'textEdit', 'plainTextEdit', 'listWidget', 'treeWidget', 'tableWidget', 'sliderWidget', 'horizontalSlider', 'verticalSlider', 'progressBar', 'dial', 'lcdNumber', 'doubleSpinBox', 'groupBox', 'frame', 'scrollArea']:
                widgets[name] = f'Q{tag[0].upper()}{tag[1:]}'
    except Exception as e:
        print(f"Error parsing {ui_file}: {e}")
        return {}

    return widgets

def generate_ui_header(ui_file, output_file):
    """Generate ui_*.h header file"""

    widgets = extract_widget_names(ui_file)

    # Get class name from UI file or use default
    try:
        tree = ET.parse(ui_file)
        root = tree.getroot()
        ns = {'ui': 'http://www.trolltech.com/forms/'}
        ui_class = root.findtext('ui:class', namespace=ns, default='twoProjectorClass')
    except:
        ui_class = 'twoProjectorClass'

    # Generate header content
    header_guard = os.path.basename(output_file).upper().replace('.', '_')

    content = f"""#ifndef {header_guard}
#define {header_guard}

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QTreeWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QSlider>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QDial>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QScrollArea>
#include <QtCore/QMetaObject>

QT_BEGIN_NAMESPACE

class {ui_class}
{{
public:
    // Widget pointers - declare all widgets referenced in your UI
"""

    # Add widget declarations
    for widget_name in sorted(widgets.keys()):
        content += f"    {widgets[widget_name]}* {widget_name}{{nullptr}};\n"

    content += f"""
    void setupUi(QMainWindow *{ui_class.lower()})
    {{
        // This is a minimal UI setup function.
        // In a real application, this would be generated by Qt's uic tool
        // and would set up all the UI elements, layouts, connections, etc.

        if ({ui_class.lower()}->objectName().isEmpty())
            {ui_class.lower()}->setObjectName(QString::fromUtf8("{ui_class}"));

        // Create central widget if needed
        if (!{ui_class.lower()}->centralWidget())
        {{
            QWidget *centralwidget = new QWidget({ui_class.lower()});
            {ui_class.lower()}->setCentralWidget(centralwidget);
        }}

        // Initialize widget pointers (actual widgets would be created in generated code)
        // This ensures ui->widgetName is valid even if not fully initialized
"""

    # Add widget initialization stubs
    for widget_name in sorted(widgets.keys()):
        if widgets[widget_name].startswith('Q'):
            content += f"        // {widget_name} would be initialized here by uic\n"

    content += f"""
        retranslateUi({ui_class.lower()});
        QMetaObject::connectSlotsByName({ui_class.lower()});
    }} // setupUi

    void retranslateUi(QMainWindow *{ui_class.lower()})
    {{
        (void){ui_class.lower()}();
    }} // retranslateUi

}}; // namespace Ui

namespace Ui {{
    class {ui_class} : public {ui_class}
    {{
    }};
}} // namespace Ui

QT_END_NAMESPACE

#endif // {header_guard}
"""

    # Write output file
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Generated {output_file}")

if __name__ == '__main__':
    ui_file = Path(__file__).parent / 'twoProjector.ui'
    output_file = Path(__file__).parent / 'ui_twoProjector.h'

    if not ui_file.exists():
        print(f"Error: {ui_file} not found")
        sys.exit(1)

    generate_ui_header(str(ui_file), str(output_file))
    print("UI header generation complete!")
